import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Chatpage(),
        ]),
      ),
    );
  }
}

class Chatpage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF01163F)),
          child: Stack(
            children: [
              Positioned(
                left: 78,
                top: 26,
                child: Container(
                  width: 92,
                  height: 88,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/92x88"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 10,
                top: 178,
                child: Container(
                  width: 56,
                  height: 56,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/56x56"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 13,
                top: 475,
                child: Container(
                  width: 56,
                  height: 56,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/56x56"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 180,
                child: Container(
                  width: 233,
                  height: 68,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF9593F7), Color(0xFF4D54EF)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 150,
                top: 342,
                child: Container(
                  width: 232,
                  height: 59,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF91C2CC), Color(0xFF37A3E0)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 186,
                top: 409,
                child: Container(
                  width: 196,
                  height: 41,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF91C2CC), Color(0xFF37A3E0)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 152,
                top: 646,
                child: Container(
                  width: 232,
                  height: 59,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF91C2CC), Color(0xFF37A3E0)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 158,
                top: 713,
                child: Container(
                  width: 225,
                  height: 39,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF91C2CC), Color(0xFF37A3E0)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 82,
                top: 483,
                child: Container(
                  width: 156,
                  height: 31,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF9593F7), Color(0xFF4D54EF)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 82,
                top: 525,
                child: Container(
                  width: 226,
                  height: 81,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF9593F7), Color(0xFF4D54EF)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 78,
                top: 260,
                child: Container(
                  width: 179,
                  height: 45,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF9593F7), Color(0xFF4D54EF)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 184,
                child: SizedBox(
                  width: 206,
                  height: 64,
                  child: Text(
                    'Congratulation Yuna for your new album !! I really love all the songs and already remember the lyrics.',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 260,
                child: SizedBox(
                  width: 148,
                  height: 45,
                  child: Text(
                    'I hope we can work in the same project later !',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 169,
                top: 347,
                child: SizedBox(
                  width: 206,
                  height: 46,
                  child: Text(
                    'Thank youu so muchhh Junho, i hope we can be in the  same project !',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 207,
                top: 419,
                child: SizedBox(
                  width: 206,
                  height: 46,
                  child: Text(
                    'Which song do you like most ?',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 94,
                top: 490,
                child: SizedBox(
                  width: 206,
                  height: 46,
                  child: Text(
                    'its hard to choose one...',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 98,
                top: 535,
                child: SizedBox(
                  width: 211,
                  child: Text(
                    'I think my favourite one is Summer Night, i love the lyrics and your voice is really wonderfull !!',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 171,
                top: 653,
                child: SizedBox(
                  width: 211,
                  child: Text(
                    'Oh My God, Thank you for listening my songs, I really appreciate it.',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 191,
                top: 27,
                child: Container(
                  width: 315,
                  height: 87,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, -0.10),
                      end: Alignment(-1, 0.1),
                      colors: [Color(0xFF54A4EE), Color(0xFFC992F5)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 28,
                        top: 15,
                        child: SizedBox(
                          width: 150,
                          height: 37,
                          child: Text(
                            'Junho',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 33,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.02,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 48,
                        child: SizedBox(
                          width: 92,
                          height: 27,
                          child: Text(
                            '@junho_32',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 776,
                child: Container(
                  width: 390,
                  height: 68,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Color(0xFF3D4B7B)),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 22,
                        top: 14,
                        child: Container(
                          width: 326,
                          height: 40,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 2,
                                color: Colors.black.withOpacity(0.20000000298023224),
                              ),
                              borderRadius: BorderRadius.circular(25),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 74,
                        top: 22,
                        child: SizedBox(
                          width: 206,
                          height: 46,
                          child: Text(
                            'Your Message...',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 15,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}