import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          cover(),
        ]),
      ),
    );
  }
}

class cover extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF00132F)),
          child: Stack(
            children: [
              Positioned(
                left: 32,
                top: 436,
                child: Container(
                  width: 341,
                  height: 322,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://cdn.discordapp.com/attachments/1151357800476328011/1153329585585401886/Atlantic_2.png"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(189),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -40,
                top: 156,
                child: Container(
                  width: 470,
                  height: 464,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://cdn.discordapp.com/attachments/1151357800476328011/1153324620733223063/Atlantic_400_400_piksel_3.png"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}