import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Chat(),
        ]),
      ),
    );
  }
}

class Chat extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFF091937), Color(0xFF0B317A)],
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 96,
                top: 165,
                child: Container(
                  width: 277,
                  height: 75,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, -0.10),
                      end: Alignment(-1, 0.1),
                      colors: [Color(0xFF54A4EE), Color(0xFFC992F5)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 29,
                        top: 20,
                        child: SizedBox(
                          width: 150,
                          height: 37,
                          child: Text(
                            'Elsie',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 33,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.02,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 48,
                        child: SizedBox(
                          width: 224,
                          height: 27,
                          child: Text(
                            'you : Apa kabar el?',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 96,
                top: 270,
                child: Container(
                  width: 277,
                  height: 75,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, -0.10),
                      end: Alignment(-1, 0.1),
                      colors: [Color(0xFF54A4EE), Color(0xFFC992F5)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 29,
                        top: 20,
                        child: SizedBox(
                          width: 150,
                          height: 37,
                          child: Text(
                            'Carin',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 33,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.02,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 48,
                        child: SizedBox(
                          width: 224,
                          height: 27,
                          child: Text(
                            'Carin :  awokwokwok',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 96,
                top: 375,
                child: Container(
                  width: 277,
                  height: 75,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, -0.10),
                      end: Alignment(-1, 0.1),
                      colors: [Color(0xFF54A4EE), Color(0xFFC992F5)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 29,
                        top: 20,
                        child: SizedBox(
                          width: 171,
                          height: 37,
                          child: Text(
                            'Jechenthia',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 33,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.02,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 48,
                        child: SizedBox(
                          width: 224,
                          height: 27,
                          child: Text(
                            'you :  kamu tim bubur apa?',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 480,
                child: Container(
                  width: 277,
                  height: 75,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, -0.10),
                      end: Alignment(-1, 0.1),
                      colors: [Color(0xFF54A4EE), Color(0xFFC992F5)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 29,
                        top: 20,
                        child: SizedBox(
                          width: 150,
                          height: 37,
                          child: Text(
                            'Chelsia',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 33,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.02,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 48,
                        child: SizedBox(
                          width: 224,
                          height: 27,
                          child: Text(
                            'Chelsia :  Jangan lupa kumpul tugas dat..',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 585,
                child: Container(
                  width: 277,
                  height: 75,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, -0.10),
                      end: Alignment(-1, 0.1),
                      colors: [Color(0xFF54A4EE), Color(0xFFC992F5)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 30,
                        top: 20,
                        child: SizedBox(
                          width: 150,
                          height: 37,
                          child: Text(
                            'Widya',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 33,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.02,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 48,
                        child: SizedBox(
                          width: 224,
                          height: 27,
                          child: Text(
                            'Widya :  MERRY SORRY BARU BLS GW ...',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 690,
                child: Container(
                  width: 277,
                  height: 75,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, -0.10),
                      end: Alignment(-1, 0.1),
                      colors: [Color(0xFF54A4EE), Color(0xFFC992F5)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 29,
                        top: 20,
                        child: SizedBox(
                          width: 150,
                          height: 37,
                          child: Text(
                            'Junho',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 33,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.02,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 48,
                        child: SizedBox(
                          width: 224,
                          height: 27,
                          child: Text(
                            'you : bales chat aku junhoo :((',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 795,
                child: Container(
                  width: 277,
                  height: 75,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, -0.10),
                      end: Alignment(-1, 0.1),
                      colors: [Color(0xFF54A4EE), Color(0xFFC992F5)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 29,
                        top: 20,
                        child: SizedBox(
                          width: 150,
                          height: 37,
                          child: Text(
                            'Hyuna',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 33,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.02,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 48,
                        child: SizedBox(
                          width: 224,
                          height: 27,
                          child: Text(
                            '@merryyy',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -13,
                top: 134,
                child: Container(
                  width: 390,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFF3A4C7B),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 77,
                child: Container(
                  width: 100,
                  height: 100,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                ),
              ),
              Positioned(
                left: 6,
                top: 375,
                child: Container(
                  width: 74,
                  height: 75,
                  decoration: ShapeDecoration(
                    color: Colors.black.withOpacity(0.20000000298023224),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 6,
                top: 690,
                child: Container(
                  width: 75,
                  height: 75,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/75x75"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 151,
                top: 77,
                child: SizedBox(
                  width: 224,
                  height: 27,
                  child: Text(
                    '@merryyy',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}