import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          FollowingProfile(),
        ]),
      ),
    );
  }
}

class FollowingProfile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF07162D)),
          child: Stack(
            children: [
              Positioned(
                left: 115,
                top: 154,
                child: SizedBox(
                  width: 173,
                  height: 46,
                  child: Text(
                    'Jechenthia',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 33,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0.02,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 161,
                top: 189,
                child: SizedBox(
                  width: 92,
                  height: 27,
                  child: Text(
                    '@jchey19_',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 115,
                top: 215,
                child: SizedBox(
                  width: 159,
                  height: 14,
                  child: Text(
                    'Hi, Iam Jechenthia\nyou can call me jechey',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 147,
                top: 51,
                child: Container(
                  width: 92,
                  height: 88,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/92x88"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 333,
                child: Opacity(
                  opacity: 0.90,
                  child: Container(
                    width: 267,
                    height: 39,
                    clipBehavior: Clip.antiAlias,
                    decoration: ShapeDecoration(
                      gradient: LinearGradient(
                        begin: Alignment(1.00, -0.10),
                        end: Alignment(-1, 0.1),
                        colors: [Color(0xFF3C99EE), Color(0xFF4B51E4)],
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 378,
                child: Opacity(
                  opacity: 0.90,
                  child: Container(
                    height: 39,
                    padding: const EdgeInsets.only(top: 8, left: 98, right: 12, bottom: 9),
                    clipBehavior: Clip.antiAlias,
                    decoration: ShapeDecoration(
                      gradient: LinearGradient(
                        begin: Alignment(1.00, -0.10),
                        end: Alignment(-1, 0.1),
                        colors: [Color(0xFF3C99EE), Color(0xFF4B51E4)],
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.end,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        SizedBox(
                          width: 157,
                          height: 22,
                          child: Text(
                            'Message',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 18,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.06,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 164,
                top: 343,
                child: SizedBox(
                  width: 157,
                  height: 22,
                  child: Text(
                    'Follow',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 18,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0.06,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 513,
                child: SizedBox(
                  width: 257,
                  height: 61,
                  child: Text(
                    'Congrats to SpaceX for completing & documented the 57 items required by the FAA for Flight 2 of Starship',
                    style: TextStyle(
                      color: Color(0xFFFFF9F9),
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 604,
                child: Container(
                  width: 137.69,
                  height: 16.32,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 19.26,
                        top: 1,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '23\n\n',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 43.33,
                        top: 16.32,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 12.82,
                            height: 24.07,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 4.84,
                                  top: -11.83,
                                  child: Container(
                                    width: 10.40,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 1,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                          color: Colors.white,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 63.59,
                        top: 1,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '19',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 106.88,
                        top: 0,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '12',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -2,
                top: 463,
                child: Container(
                  width: 390,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFF3A4C7B),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 2,
                top: 439,
                child: SizedBox(
                  width: 95,
                  height: 25,
                  child: Text(
                    'Blues',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 268,
                child: Container(
                  width: 311,
                  height: 53.17,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 28.25,
                        child: SizedBox(
                          width: 57.82,
                          height: 24.92,
                          child: Text(
                            'Blues',
                            style: TextStyle(
                              color: Color(0xFFF1F1F1),
                              fontSize: 16,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 5.50,
                        top: 0,
                        child: SizedBox(
                          width: 57.82,
                          height: 24.92,
                          child: Text(
                            '734',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 131.28,
                        top: 0,
                        child: SizedBox(
                          width: 57.82,
                          height: 24.92,
                          child: Text(
                            '678',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 248,
                        top: 2,
                        child: SizedBox(
                          width: 57.82,
                          height: 24.92,
                          child: Text(
                            '982',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 226.02,
                        top: 26.08,
                        child: SizedBox(
                          width: 84.98,
                          height: 24.92,
                          child: Text(
                            'Following',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 110.88,
                        top: 27.25,
                        child: SizedBox(
                          width: 80.60,
                          height: 22.42,
                          child: Text(
                            'Followers',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 728,
                child: Container(
                  width: 143,
                  height: 19,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 20,
                        top: 0,
                        child: SizedBox(
                          width: 32,
                          height: 13,
                          child: Text(
                            '23\n\n',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 45,
                        top: 19,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 17,
                            height: 25,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 5.02,
                                  top: -15.69,
                                  child: Container(
                                    width: 10.80,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 1,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                          color: Colors.white,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 65,
                        top: 0,
                        child: SizedBox(
                          width: 32,
                          height: 13,
                          child: Text(
                            '19',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 111,
                        top: 0,
                        child: SizedBox(
                          width: 32,
                          height: 13,
                          child: Text(
                            '12',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 145,
                top: 440,
                child: SizedBox(
                  width: 95,
                  height: 25,
                  child: Text(
                    'Media',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 292,
                top: 440,
                child: SizedBox(
                  width: 95,
                  height: 25,
                  child: Text(
                    'Likes',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}