import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Homepage(),
        ]),
      ),
    );
  }
}

class Homepage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF011635)),
          child: Stack(
            children: [
              Positioned(
                left: -1990,
                top: 175,
                child: Container(
                  width: 390,
                  height: 844,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(
                    color: Color(0xFF041530),
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 170.50,
                        top: 3,
                        child: Container(width: 49, height: 53),
                      ),
                      Positioned(
                        left: 17,
                        top: 187,
                        child: Container(
                          width: 354,
                          height: 586,
                          decoration: BoxDecoration(color: Color(0x33030A4F)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 104,
                top: 214,
                child: SizedBox(
                  width: 115,
                  height: 19,
                  child: Text(
                    'Elsie',
                    style: TextStyle(
                      color: Color(0xFFF5F5F5),
                      fontSize: 14,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0.10,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 112,
                top: 246,
                child: SizedBox(
                  width: 272,
                  height: 61,
                  child: Text(
                    'The only thing we have to fear is fear itself.\nGood Luck!',
                    style: TextStyle(
                      color: Color(0xFFFFF9F9),
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 105,
                top: 311,
                child: Container(
                  width: 143,
                  height: 19,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 20,
                        top: 0,
                        child: SizedBox(
                          width: 32,
                          height: 13,
                          child: Text(
                            '23\n\n',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 45,
                        top: 19,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 17,
                            height: 25,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 5.02,
                                  top: -15.69,
                                  child: Container(
                                    width: 10.80,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 1,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                          color: Colors.white,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 65,
                        top: 0,
                        child: SizedBox(
                          width: 32,
                          height: 13,
                          child: Text(
                            '19',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 111,
                        top: 0,
                        child: SizedBox(
                          width: 32,
                          height: 13,
                          child: Text(
                            '12',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 106,
                top: 447,
                child: Container(
                  width: 246,
                  height: 231.82,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 24.49,
                        child: Container(
                          width: 242,
                          height: 63,
                          decoration: ShapeDecoration(
                            gradient: SweepGradient(
                              center: Alignment(2.26, 0.13),
                              startAngle: 0.77,
                              endAngle: 0.88,
                              colors: [Color(0xFF517EF4), Color(0xFF648BFA), Color(0xFF0445EB)],
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1,
                        top: 163.49,
                        child: Container(
                          width: 237.82,
                          height: 43.72,
                          decoration: ShapeDecoration(
                            gradient: SweepGradient(
                              center: Alignment(2.26, 0.13),
                              startAngle: 0.77,
                              endAngle: 0.88,
                              colors: [Color(0xFF517EF4), Color(0xFF648BFA), Color(0xFF0445EB)],
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 12.99,
                        top: 26.11,
                        child: SizedBox(
                          width: 233.01,
                          height: 55.03,
                          child: Text(
                            'Congrats to SpaceX for completing & documented the 57 items required by the FAA for Flight 2 of Starship',
                            style: TextStyle(
                              color: Color(0xFFFFF9F9),
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0.14,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1,
                        top: 97.49,
                        child: Container(
                          width: 137.69,
                          height: 16.32,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 19.26,
                                top: 2,
                                child: SizedBox(
                                  width: 30.81,
                                  height: 9.80,
                                  child: Text(
                                    '23\n\n',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 43.33,
                                top: 16.32,
                                child: Transform(
                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                                  child: Container(
                                    width: 12.82,
                                    height: 24.07,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 4.84,
                                          top: -11.83,
                                          child: Container(
                                            width: 10.40,
                                            decoration: ShapeDecoration(
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 1,
                                                  strokeAlign: BorderSide.strokeAlignCenter,
                                                  color: Colors.white,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 62.59,
                                top: 2,
                                child: SizedBox(
                                  width: 30.81,
                                  height: 9.80,
                                  child: Text(
                                    '19',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 106.88,
                                top: 0,
                                child: SizedBox(
                                  width: 30.81,
                                  height: 9.80,
                                  child: Text(
                                    '12',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1,
                        top: 217.49,
                        child: Container(
                          width: 137.69,
                          height: 14.32,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 19.26,
                                top: -0,
                                child: SizedBox(
                                  width: 30.81,
                                  height: 9.80,
                                  child: Text(
                                    '23\n\n',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 43.33,
                                top: 14.32,
                                child: Transform(
                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                                  child: Container(
                                    width: 12.82,
                                    height: 24.07,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 4.84,
                                          top: -11.83,
                                          child: Container(
                                            width: 10.40,
                                            decoration: ShapeDecoration(
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 1,
                                                  strokeAlign: BorderSide.strokeAlignCenter,
                                                  color: Colors.white,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 62.59,
                                top: -0,
                                child: SizedBox(
                                  width: 30.81,
                                  height: 9.80,
                                  child: Text(
                                    '19',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 106.88,
                                top: -0,
                                child: SizedBox(
                                  width: 30.81,
                                  height: 9.80,
                                  child: Text(
                                    '12',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0.25,
                        top: 0,
                        child: SizedBox(
                          width: 110.73,
                          height: 14.32,
                          child: Text(
                            'Chelsia',
                            style: TextStyle(
                              color: Color(0xFFF5F5F5),
                              fontSize: 14,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.10,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 13,
                        top: 165.49,
                        child: SizedBox(
                          width: 214.72,
                          height: 15.08,
                          child: Text(
                            'PEACEMINUSONE X NIKE ‘KILLONDO1’ COMING SOON !',
                            style: TextStyle(
                              color: Color(0xFFFFF9F9),
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0.14,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 110,
                top: 411,
                child: Container(
                  width: 143,
                  height: 19,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 20,
                        top: 0,
                        child: SizedBox(
                          width: 32,
                          height: 13,
                          child: Text(
                            '23\n\n',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 45,
                        top: 19,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 17,
                            height: 25,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 5.02,
                                  top: -15.69,
                                  child: Container(
                                    width: 10.80,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 1,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                          color: Colors.white,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 65,
                        top: 0,
                        child: SizedBox(
                          width: 32,
                          height: 13,
                          child: Text(
                            '19',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 111,
                        top: 0,
                        child: SizedBox(
                          width: 32,
                          height: 13,
                          child: Text(
                            '12',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 106,
                top: 341,
                child: SizedBox(
                  width: 115,
                  height: 19,
                  child: Text(
                    'Widya',
                    style: TextStyle(
                      color: Color(0xFFF5F5F5),
                      fontSize: 14,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0.10,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 111,
                top: 373,
                child: SizedBox(
                  width: 249,
                  height: 41,
                  child: Text(
                    ' Hello World !',
                    style: TextStyle(
                      color: Color(0xFFFFF9F9),
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 106,
                top: 584.49,
                child: SizedBox(
                  width: 115,
                  height: 19,
                  child: Text(
                    'Carin',
                    style: TextStyle(
                      color: Color(0xFFF5F5F5),
                      fontSize: 14,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0.10,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 102,
                child: SizedBox(
                  width: 243,
                  height: 67,
                  child: Text(
                    'Hello, Merry',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 40,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0.01,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 84.99,
                top: 145,
                child: Container(
                  width: 25,
                  height: 28,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(children: [
                  ]),
                ),
              ),
              Positioned(
                left: 27,
                top: 142,
                child: Container(
                  width: 30,
                  height: 33,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(children: [
                  ]),
                ),
              ),
              Positioned(
                left: 92,
                top: 208,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.56),
                  child: Container(
                    width: 116,
                    decoration: ShapeDecoration(
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          strokeAlign: BorderSide.strokeAlignCenter,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 93.01,
                top: 341,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  child: Container(
                    width: 89,
                    decoration: ShapeDecoration(
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          strokeAlign: BorderSide.strokeAlignCenter,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 93,
                top: 450.49,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  child: Container(
                    width: 109,
                    decoration: ShapeDecoration(
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          strokeAlign: BorderSide.strokeAlignCenter,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 93,
                top: 586.49,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  child: Container(
                    width: 88,
                    decoration: ShapeDecoration(
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          strokeAlign: BorderSide.strokeAlignCenter,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -87,
                top: -37,
                child: Container(
                  width: 336,
                  height: 258,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 336,
                          height: 258,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/336x258"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 58,
                        child: Container(
                          width: 69,
                          height: 35,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/69x35"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 697,
                child: Container(
                  width: 315,
                  height: 113,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 76.69,
                        top: 24.32,
                        child: Container(
                          width: 234.44,
                          height: 62.55,
                          decoration: ShapeDecoration(
                            gradient: SweepGradient(
                              center: Alignment(2.26, 0.13),
                              startAngle: 0.77,
                              endAngle: 0.88,
                              colors: [Color(0xFF517EF4), Color(0xFF648BFA), Color(0xFF0445EB)],
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 89.27,
                        top: 25.92,
                        child: SizedBox(
                          width: 225.73,
                          height: 54.64,
                          child: Text(
                            'Congrats to SpaceX for completing & documented the 57 items required by the FAA for Flight 2 of Starship',
                            style: TextStyle(
                              color: Color(0xFFFFF9F9),
                              fontSize: 12,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0.14,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 77.66,
                        top: 96.79,
                        child: Container(
                          width: 133.38,
                          height: 16.21,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 18.66,
                                top: 1.99,
                                child: SizedBox(
                                  width: 29.85,
                                  height: 9.73,
                                  child: Text(
                                    '23\n\n',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 41.97,
                                top: 16.21,
                                child: Transform(
                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                                  child: Container(
                                    width: 12.72,
                                    height: 23.32,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 4.68,
                                          top: -11.74,
                                          child: Container(
                                            width: 10.08,
                                            decoration: ShapeDecoration(
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 1,
                                                  strokeAlign: BorderSide.strokeAlignCenter,
                                                  color: Colors.white,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 60.63,
                                top: 1.99,
                                child: SizedBox(
                                  width: 29.85,
                                  height: 9.73,
                                  child: Text(
                                    '19',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 103.54,
                                top: 0,
                                child: SizedBox(
                                  width: 29.85,
                                  height: 9.73,
                                  child: Text(
                                    '12',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 55,
                          height: 55,
                          decoration: ShapeDecoration(
                            color: Colors.black.withOpacity(0.20000000298023224),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 76.93,
                        top: 0,
                        child: SizedBox(
                          width: 107.27,
                          height: 14.22,
                          child: Text(
                            'Jechenthia',
                            style: TextStyle(
                              color: Color(0xFFF5F5F5),
                              fontSize: 14,
                              fontFamily: 'Sen',
                              fontWeight: FontWeight.w700,
                              height: 0.10,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 93,
                top: 697.49,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  child: Container(
                    width: 109,
                    decoration: ShapeDecoration(
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          strokeAlign: BorderSide.strokeAlignCenter,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}