import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ProfilePage(),
        ]),
      ),
    );
  }
}

class ProfilePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF102C55)),
          child: Stack(
            children: [
              Positioned(
                left: 135,
                top: 171,
                child: SizedBox(
                  width: 120,
                  height: 37,
                  child: Text(
                    'Merry',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 40,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0.01,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 162,
                top: 208,
                child: SizedBox(
                  width: 92,
                  height: 27,
                  child: Text(
                    '@merryyy',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 118,
                top: 243,
                child: SizedBox(
                  width: 159,
                  height: 14,
                  child: Text(
                    'Yoona from Girls’ Generation\nSM Entertainment\n',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 382.04,
                top: -81,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.90),
                  child: Container(
                    width: 152.17,
                    height: 192.19,
                    decoration: ShapeDecoration(
                      color: Color(0xFF0748F1),
                      shape: OvalBorder(side: BorderSide(width: 1)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27.05,
                top: 24,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.90),
                  child: Container(
                    width: 126.07,
                    height: 137.48,
                    decoration: ShapeDecoration(
                      color: Color(0xFF8E00FF),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 480,
                child: Container(
                  width: 230,
                  height: 141,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/230x141"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 433,
                child: SizedBox(
                  width: 249,
                  height: 41,
                  child: Text(
                    'PEACEMINUSONE X NIKE ‘KILLONDO1’ COMING SOON !',
                    style: TextStyle(
                      color: Color(0xFFFFF9F9),
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 651,
                child: Container(
                  width: 137.69,
                  height: 16.32,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 19.26,
                        top: 1,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '23\n\n',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 43.33,
                        top: 16.32,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 12.82,
                            height: 24.07,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 4.84,
                                  top: -11.83,
                                  child: Container(
                                    width: 10.40,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 1,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                          color: Colors.white,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 63.59,
                        top: 1,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '19',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 106.88,
                        top: 0,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '12',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 651,
                child: Container(
                  width: 137.69,
                  height: 16.32,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 19.26,
                        top: 1,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '23\n\n',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 43.33,
                        top: 16.32,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 12.82,
                            height: 24.07,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 4.84,
                                  top: -11.83,
                                  child: Container(
                                    width: 10.40,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 1,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                          color: Colors.white,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 63.59,
                        top: 1,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '19',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 106.88,
                        top: 0,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '12',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 794,
                child: Container(
                  width: 137.69,
                  height: 16.32,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 19.26,
                        top: 1,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '23\n\n',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 43.33,
                        top: 16.32,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 12.82,
                            height: 24.07,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 4.84,
                                  top: -11.83,
                                  child: Container(
                                    width: 10.40,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 1,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                          color: Colors.white,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 63.59,
                        top: 1,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '19',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 106.88,
                        top: 0,
                        child: SizedBox(
                          width: 30.81,
                          height: 9.80,
                          child: Text(
                            '12',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 696,
                child: SizedBox(
                  width: 257,
                  height: 61,
                  child: Text(
                    'Congrats to SpaceX for completing & documented the 57 items required by the FAA for Flight 2 of Starship',
                    style: TextStyle(
                      color: Color(0xFFFFF9F9),
                      fontSize: 12,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0.14,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 3,
                top: 380,
                child: SizedBox(
                  width: 95,
                  height: 25,
                  child: Text(
                    'Blues',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 143,
                top: 381,
                child: SizedBox(
                  width: 95,
                  height: 25,
                  child: Text(
                    'Media',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 284,
                top: 381,
                child: SizedBox(
                  width: 95,
                  height: 25,
                  child: Text(
                    'Likes',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Sansation',
                      fontWeight: FontWeight.w400,
                      height: 0,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 400,
                child: Container(
                  width: 390,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFF3A4C7B),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 288,
                child: Container(
                  width: 311,
                  height: 53.17,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 28.25,
                        child: SizedBox(
                          width: 57.82,
                          height: 24.92,
                          child: Text(
                            'Blues',
                            style: TextStyle(
                              color: Color(0xFFF1F1F1),
                              fontSize: 16,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 5.50,
                        top: 0,
                        child: SizedBox(
                          width: 57.82,
                          height: 24.92,
                          child: Text(
                            '734',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 131.28,
                        top: 0,
                        child: SizedBox(
                          width: 57.82,
                          height: 24.92,
                          child: Text(
                            '678',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 248,
                        top: 2,
                        child: SizedBox(
                          width: 57.82,
                          height: 24.92,
                          child: Text(
                            '982',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 226.02,
                        top: 26.08,
                        child: SizedBox(
                          width: 84.98,
                          height: 24.92,
                          child: Text(
                            'Following',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 110.88,
                        top: 27.25,
                        child: SizedBox(
                          width: 80.60,
                          height: 22.42,
                          child: Text(
                            'Followers',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontFamily: 'Sansation',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}