import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          SignUp(),
        ]),
      ),
    );
  }
}

class SignUp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFF000D17), Color(0xFF000B6F)],
            ),
            boxShadow: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 110,
                top: 682,
                child: Container(
                  width: 10,
                  height: 10,
                  decoration: ShapeDecoration(
                    color: Colors.white.withOpacity(0.800000011920929),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 76,
                child: SizedBox(
                  width: 179,
                  height: 44,
                  child: Text(
                    'Sign Up',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 40,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0.01,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 169,
                child: Container(
                  width: 307,
                  height: 498,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 307,
                          height: 498,
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.18000000715255737),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 18,
                                child: SizedBox(
                                  width: 95,
                                  height: 25,
                                  child: Text(
                                    'First Name',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 16,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 11,
                                top: 117,
                                child: SizedBox(
                                  width: 95,
                                  height: 25,
                                  child: Text(
                                    'Last Name',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 16,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: -8,
                                top: 220,
                                child: SizedBox(
                                  width: 95,
                                  height: 25,
                                  child: Text(
                                    'Email',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 16,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 11,
                                top: 319,
                                child: SizedBox(
                                  width: 95,
                                  height: 25,
                                  child: Text(
                                    'Password',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 16,
                                      fontFamily: 'Sansation',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 28,
                        top: 49,
                        child: Container(
                          width: 260,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.800000011920929),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 151,
                        child: Container(
                          width: 260,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.800000011920929),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 24,
                        top: 252,
                        child: Container(
                          width: 260,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.800000011920929),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 346,
                        child: Container(
                          width: 260,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.800000011920929),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 429,
                        child: Container(
                          width: 307,
                          height: 66,
                          padding: const EdgeInsets.only(top: 23, left: 98, right: 30),
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(1.00, -0.10),
                              end: Alignment(-1, 0.1),
                              colors: [Color(0xFF54A4EE), Color(0xFFC992F5)],
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.end,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              SizedBox(
                                width: 179,
                                height: 44,
                                child: Text(
                                  'Confirm',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 28,
                                    fontFamily: 'Sen',
                                    fontWeight: FontWeight.w700,
                                    height: 0.03,
                                    letterSpacing: -0.30,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 62,
                top: 218,
                child: Container(
                  width: 264,
                  height: 347,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 4,
                        top: 0,
                        child: Container(
                          width: 260,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.800000011920929),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 2,
                        top: 102,
                        child: Container(
                          width: 260,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.800000011920929),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 203,
                        child: Container(
                          width: 260,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.800000011920929),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 2,
                        top: 297,
                        child: Container(
                          width: 260,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.800000011920929),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 131,
                top: 681,
                child: Text(
                  'I agree with Terms and Privacy',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 10,
                    fontFamily: 'Sansation',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}