import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Trendingpage(),
        ]),
      ),
    );
  }
}

class Trendingpage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF00132A)),
          child: Stack(
            children: [
              Positioned(
                left: 34,
                top: 149,
                child: Container(
                  width: 230,
                  height: 72,
                  decoration: ShapeDecoration(
                    color: Color(0x3FB99EE5),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 120,
                top: 401,
                child: Container(
                  width: 238,
                  height: 79,
                  decoration: ShapeDecoration(
                    color: Color(0x3F689E77),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 89,
                top: 539,
                child: Container(
                  width: 238,
                  height: 79,
                  decoration: ShapeDecoration(
                    color: Color(0x3FA79372),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 160,
                top: 558,
                child: SizedBox(
                  width: 155,
                  height: 28,
                  child: Text(
                    'Cryptocurrency',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 82,
                top: 268,
                child: Container(
                  width: 238,
                  height: 79,
                  decoration: ShapeDecoration(
                    color: Color(0x3F8EB9D8),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 689,
                child: Container(
                  width: 239,
                  height: 79,
                  decoration: ShapeDecoration(
                    color: Color(0x3FBA757B),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 702,
                child: SizedBox(
                  width: 170,
                  child: Text(
                    'Teknologi \nTerkini',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 108,
                top: 166,
                child: SizedBox(
                  width: 122,
                  height: 37,
                  child: Text(
                    'Pemilu 2024',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 145,
                top: 289,
                child: SizedBox(
                  width: 170,
                  height: 25,
                  child: Text(
                    'Kampus Terbaik',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 65,
                child: SizedBox(
                  width: 282,
                  height: 62,
                  child: Text(
                    'Trending Page',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 40,
                      fontFamily: 'Sen',
                      fontWeight: FontWeight.w700,
                      height: 0.01,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}